### ISSUE TITLE
Update PERAC with USDA MACC curve data, add new ag/land policies to match

### ISSUE THREAD

**Issue by oashmoore** [Energy-Innovation/eps-us#187] opened 2021-09-15 20:38 UTC
Consider updating PERAC cost cuves using US data set from this paper: 
https://www.usda.gov/sites/default/files/documents/White_Paper_WEB71816.pdf 

In the future, consider updating policy levers to align with MACC curves. 

Using the attached data
[MACC Data.xlsx](https://github.com/Energy-Innovation/eps-us/files/7173088/MACC.Data.xlsx)

**Comment by jrissman** [comment] 2022-02-16 21:33
Closing as duplicate of issue #201.  Note that more recent data are available than what are linked here.

**Closed by jrissman** 2022-02-16 21:33 UTC
Labels: low priority
