### ISSUE TITLE
Reclassify construction as a separate industry

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#105] opened 2020-10-28 14:53 UTC
We currently group all non-specifically broken out industries in the EPS into the "other industries" category, including when trying to allocate costs and changes to expenditures and revenue. As an example, when adding CCS in industry, we might see that the other industries category incurs very high costs to install and operate the equipment. When we then allocate costs to ISIC codes, we are assigning the total change in spending in the other industries category based on the BAU output of that group of industries. This makes sense for most industries in this bucket but not for construction. 

Construction output is tied to spending in other sectors beyond the industry sector, and proportionally assigning other industry revenue and expense changes to construction based on its share of BAU output among other industries is not accurate. More importantly, when other industry expenses change, it is incorrect to group construction as part of this, as construction revenues would often be expected to _increase_  when industry sector expenses increase to comply with a policy. For example, in the CCS scenario, we would expect many construction jobs to build the CCS equipment (which the model calculates correctly) but we wouldn't expect the construction industry itself to incur costs to comply with a CCS requirement (which the model is calculating). With the current structure, we see a large decrease in construction jobs because the net impact on the construction sector after proportionally assigning non-industry sector costs results in a net negative cash flow (testing this in the VA model).

The cleanest way (I believe) to do this is to remove construction from the other industries category in the ISIC code grouping and ultimately in the sector grouping as well. We have data from EIA on construction energy use so it may be the case that making this change ultimately pushes us to make construction its own industry (along with others, as previously discussed).

**Comment by jrissman** [comment] 2020-10-28 20:07
I think it would be a good idea to break out construction as an industry as part of #89.  This should address the issues you raised because policy effects applied to the "other industries" category would not be applying to the construction industry anymore - the policy would have to be intentionally applied to the "construction" industry.  We wouldn't do that where it doesn't make sense - e.g. we would not have the construction industry utilize CCS themselves.  (The construction industry already, in 3.0.0, gets revenue for installing CCS systems bought by others, so we don't have to do anything special there.)

Yes, I think construction would probably also need to be removed from the "other industries ISIC code" sub-range.  The other industries we break out as part of #89 might need this also.  I'll resolve these technical implementation details as part of work on #89.

**Comment by robbieorvis** [comment] 2020-10-28 20:40
Just to add some additional context, this issue is particularly pronounced in regions that are largely service based and extends beyond just construction.

As another example, let's say that an industry's industrial energy consumption is evenly split across all the industry categories in the model, but it has a huge services sector - much larger than any of the manufacturing sectors. This means that in terms of $ output, the majority of $ output is going to be in the "other industries" category as it is currently defined. When we institute a policy that increases energy prices and causes a reduction in demand/production for the other industries category, we can get a very large $ change in output relative to the other industries because BAU output and BAU Nonfuel revenue by industry is counting revenue and output coming from the services sector. Downstream of this, we get weird impacts because the changes are being applied to non-manufacturing (i.e. service) industries.

**Comment by jrissman** [comment] 2020-10-28 20:43
I don't think this follow-up example is correct, because I was careful to exclude the service industries' ISIC codes from the "Other Industries Category ISIC Code" sub-range in 3.0.0.  This sub-range only includes manufacturing industries and construction.

![OIC_Isic](https://user-images.githubusercontent.com/7120106/97494367-71e03180-1923-11eb-8218-cf84480faa1c.PNG)

**Comment by robbieorvis** [comment] 2020-10-28 20:52
Hm okay, it may be the case then that the issue is primarily limited to construction.

In that case, is one short term solution (notwithstanding energy consumption issues – though I suspect construction energy consumption is small in comparison to other manufacturing) – to simply change the subgroupings to move construction to a different subgroup? I’m probably dramatically oversimplifying, but just a thought.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment] 2020-10-28 20:57
Yeah, that would likely be possible even before/without working on #89.  Let me look into it and see if I can do that quick fix today.

**Comment by robbieorvis** [comment] 2020-10-28 21:00
Okay – fingers crossed! That would resolve some challenges on the state model side.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment] 2020-10-29 00:37
This is done in commit 322f312.  I've done some basic testing and examining of the model and seems to work.  However, I am not going to close this issue yet because I can't easily test the specific effect you described above.  **Could you please re-test it using commit 322f312 and see if it fixed the issue?**

Note that I needed to remove construction from two subranges, "Other Industries Category ISIC Code" and "Nonenergy Industries ISIC Code," both of which are used to divide up certain industrial quantities among industries.  (The difference is whether or not they exclude the separately-broken-out non-energy industries like "iron and steel" or "chemicals".)  I did not alter the "Manufacturing and Construction ISIC Code" subrange, as that subrange is only used for grouping economic output on the final graphs, and isn't used internally for calculations, and I didn't want to change the meaning of the final graphs.

One other note is that because I think the AEO data we use for Total Industrial Energy Use (in BIFUbC) included construction (as part of the AEO's "nonmanufacturing sector," along with mining and agriculture), that energy use is still part of the "Other Industries" category (we haven't removed this energy use from the model, and we currently have no "construction" industry category to assign it to).  But policy-driven costs related to this energy use (such as cash flow changes caused by industrial efficiency standards applied to the "other industries" category) are now being shared among the remaining industries within the "other industries" category - that is, construction no longer receiving a share of those cost changes.  I don't think this is a big deal because construction's own energy use is not large (remember trucks are part of the Transport sector), and the effects on any model outputs will be minimal (it might very slightly overstate costs or savings to other non-energy industries and assign less to construction, but they get grouped with construction in the financial output graphs anyway).  The way to achieve exact precision here would be to implement issue #89, which is a big job, and is saved for later.

I'll close this issue if you can test and determine that this quick fix is good enough for now.

**Comment by robbieorvis** [comment] 2020-10-29 13:49
This is great and it fixes the issue I identified! I’m exploring one other issue, that I don’t think is related to this but just double checking, so don’t close it quite yet.

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by robbieorvis** [comment] 2020-10-29 14:53
Okay, just some follow-up. This might warrant a different issue, but it is related.

One challenge I’m running into is the way in which we divvy up policy costs to the other industries sector in assigning them to them the ISIC codes that make up that sector.

For example, food, tobacco, and beverage is a big industry in Virginia, but as a source of emissions/energy use in Virginia I suspect it is quite small. Nationally, another example is paper in pulp, but in the opposite direction.

Currently, when we assign policy costs the other industries ISIC codes, we do so proportionally based on BAU output, but I’m wondering if we shouldn’t instead do this based on BAU amount spent on the utilities sector (ISIC 35T39) from each ISIC code. This isn’t perfect, but it does a better job capturing how energy/emissions policies might affect certain ISIC codes more than others, relating this to the amount they spend on utilities instead of what they produce. This would likely better represent how energy and climate policies might affect the specific other industries. This would fix an issue where a very low energy intensity industry might end up with a very high economic impact from a policy, even though in reality it uses far less energy than other emitting industries.

I believe you calculate this all internally in Vensim by multiplying the BAU output variable by the DLIM value from the utilities sector to each sector, then dividing by the total spend on the utilities sector to develop a fraction of other industries costs that should be assigned to each ISIC code.

What do you think?

________________________________
Robbie Orvis
Director of Energy Policy Design
Phone: 415-799-2171
98 Battery Street, Suite 202
San Francisco, CA  94111
www.energyinnovation.org<http://www.energyinnovation.org/>
[cid:image001.jpg@01D0D699.20A24470]
________________________________

Check out our new book, Designing Climate Solutions: A Policy Guide for Low-Carbon Energy<https://www.amazon.com/Designing-Climate-Solutions-Policy-Low-Carbon/dp/1610919564>
Available wherever books are sold

[Policy Design book cover]

**Comment by jrissman** [comment] 2020-10-29 18:55
That is a good idea for a methodology of how to divide up policy compliance costs (and fuel savings, etc.) among different ISIC codes within the "other industries" category.

It doesn't have to do with "Reclassify construction as a separate industry" because that was done, and construction is no longer part of the Other Industries category for purposes of assigning costs/savings by output.  So I've made a new issue for this request.  I'm closing this issue.

**Closed by jrissman** 2020-10-29 18:55 UTC
Labels: medium priority
