### ISSUE TITLE
Disaggregate f-gas emissions into chemicals, other metals, and electronics

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#190] opened 2021-09-28 21:33 UTC
Now that we have more industry detail, @robbieorvis and I were discussing distributing f-gas emissions between the relevant industries rather than just chemicals, which would also include emissions from the aluminum/other metals and electronics industries. This would require new levers in PERAC for these industries, but could improve accuracy especially in countries like China which have a lot of aluminum manufacturing. This update would also help improve accuracy around the jobs/GDP results for these industries.

**Comment by jrissman** [comment] 2021-09-28 21:48
Closing as duplicate of issue #178

**Closed by jrissman** 2021-09-28 21:48 UTC
Labels: low priority, 3.4
