### ISSUE TITLE
Separate policy implementation schedule settings for different efficiency settings

### ISSUE THREAD

**Issue by oashmoore** [Energy-Innovation/eps-us#103] opened 2020-10-27 21:30 UTC
Building efficiency policy setting is set in the same policy schedule. As we're modelling state legislative goals and policy scenarios, we're finding many policies that set different targets and timelines for residential and commercial buildings. It is difficult to represent with only one policy schedule. Ideally, there would be separate policy implementation schedules for building subsectors.

**Comment by jrissman** [comment] 2020-10-28 20:12
Closing as a duplicate of #16

**Closed by jrissman** 2020-10-28 20:12 UTC
Labels: duplicate, medium priority
