### ISSUE TITLE
Add in BAU Hydrogen Demand for Industry and Adjust BIFUbC

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#197] opened 2021-11-01 13:46 UTC
Currently, all H2 demand in the EPS is from the transportation sector, but there is actually a considerable amount of H2 demand in industry, about 60 MMT CO2e/11.4 MMT H2 per year. It is produced by a mix of refineries, merchant H2 facilities, and chemical plants. We should update BIFUbC accordingly to properly account for these emissions (and to be able to evaluate H2 policies in the absence of large increases in demand for H2). 

There are several good data sources for this:

Data on BAU demand by industrial sector: https://cafcp.org/sites/default/files/Road+Map+to+a+US+Hydrogen+Economy+Full+Report.pdf

Data on BAU supply by industrial sector: https://www.epa.gov/sites/default/files/2015-02/documents/subpartp-tsd_hydrogenproduction.pdf

Additional data and sources for supply: https://www.hydrogen.energy.gov/pdfs/19002-hydrogen-market-domestic-global.pdf

Data on natural gas feedstock use for H2 at refineries: https://www.eia.gov/dnav/pet/pet_pnp_feedng_k_a.htm

**Comment by jrissman** [comment] 2021-11-01 18:30
The EPS was designed to track electricity, heat, and hydrogen made and used internally within industrial facilities as the fuel or electricity used to make the energy carrier.  It doesn't currently include fuel transformations that occur within individual industrial facilities.

If you make the data-only change here, keep in mind:

* You would need to manually remove any fuel and electricity use by industry to create hydrogen from BIFUbC, to avoid double-counting
* Fuel use and emissions from Industry would probably no longer match published emissions inventories, because the energy and emissions used by Industry to make hydrogen would be assigned to the "District Heat and Hydrogen Sector" in the model and in output graphs, not to the Industry sector
* When policies affect this hydrogen production, their cash flows will be assigned to the hydrogen supply industry, not to the individual Industry sector industries that actually undertook the relevant measures.

Almost all hydrogen used by industry today is used as feedstocks, not burned for energy.  (A small amount of H2 that is mixed with other gases, as a component of blast furnace top gas, is collected and burned within the iron and steel facility for heat.  It never is separated out as pure hydrogen.)  Handling decarbonization for industrial feedstocks is on GitHub as issue #181, which I regarded as High Priority.

Another relevant issue is the one Robbie opened regarding energy transformations within industry, #169.  That topic also interacts with this.

If you still want to, you can go ahead and do the data-only edit in this issue as a temporary measure for 3.3.1 (including removing the fuel/electricity use from BIFUbC to avoid double-counting, per the first bullet above).  In fact, knowing the amount of fuel and electricity used to make hydrogen would be useful because we need to know that when implementing #169 or #181.  But we will ultimately want to handle this in dedicated industry fuel transformation and/or feedstock code per issues #169 and #181.

**Comment by jrissman** [comment] 2021-12-16 00:29
This item was moved to the eps-us-analysis issue tracker since it pertains to that model deployment rather than to the eps-us model deployment.  Closing this.

**Closed by jrissman** 2021-12-16 00:29 UTC
Labels: data only, high priority, 3.3.1, us-analysis branch
