### ISSUE TITLE
Reconsider metrics to use in transportation sector macroeconomic feedbacks

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#242] opened 2022-06-09 22:46 UTC
While working on the US model, I realized that the Buy In Region lever causes changes in transportation demand, since the macroeconomic feedbacks in the transportation sector are based on changes to ISIC codes 29 and 30. However, just because consumers are buying domestically produced cars rather than imported cars doesn't mean the demand for vehicle-miles should change. 

It seems like we may be able to land on more representative metrics for the transportation feedbacks. For example, freight transportation is probably more correlated with overall GDP than the ISIC codes for vehicle manufacturing (since freight vehicles are transporting goods produced by various industries). Robbie suggested he may have a data set that could allocate freight distance by ISIC code, which could help us determine feedbacks based on changes in GDP. For passenger modes, I would think something like household spending would be a better indicator.

This would have an immediate impact on the reconciliation work we're doing, so I'm tentatively tagging this as 3.4 if we think it's something easy enough to finish off in the next week or so as we're finalizing things.

**Comment by jrissman** [comment] 2022-06-09 22:50
Our plan was to move to OECD's larger ISIC code breakout for 3.5, which includes an ISIC code explicitly for freight transportation services.  Then we would base the transportation feedback loop on that ISIC code rather than on vehicle manufacturing.  But it's not practical to move to OECD's new ISIC codes until 3.5.  If you want to temporarily use something other than vehicle manufacturing, like total industrial output, to estimate change in freight demand in 3.4, we could probably do that.  But I don't think we should spend much time on coming up with a complicated procedure like you describe in your second paragraph because we planned to use the explicit freight transportation services ISIC code once we move to 3.5, and the DLIM tables, etc. should contain the extent to which all the industries demand freight transport services, so we don't need to calculate that ourselves once we move to new OECD isic codes.

**Comment by jrissman** [comment] 2022-06-09 22:52
Also, closing this as duplicate of issue #117.  Please update that issue if anything new has arisen.

**Closed by jrissman** 2022-06-09 22:52 UTC
Labels: 3.4
