### ISSUE TITLE
Create linkage between biofuel demand and land sector

### ISSUE THREAD

**Issue by robbieorvis** [Energy-Innovation/eps-us#91] opened 2020-08-27 16:32 UTC
In a call with WRI Indonesia, Arief pointed out how the government is evaluating biodiesel policies that could have a profound impact on land related emissions since it involves displacing land to grow palm oil within Indonesia. Now that we are updating the Indonesia model and also finishing the Brazil (where ethanol produced domestically is used in vehicles) model, it may make sense to revisit the idea of linking biofuel demand with land use emissions. WRI Indonesia has offered to share insights on this relationship if we want to consider building it into the model.

**Comment by jrissman** [comment] 2020-08-27 21:40
Closing this as a duplicate of issue #14

**Closed by jrissman** 2020-08-27 21:40 UTC
Labels: duplicate, medium priority
