### ISSUE TITLE
Link biofuel demand to agriculture/land use

### ISSUE THREAD

**Issue by mkmahajan** [Energy-Innovation/eps-us#126] opened 2020-12-04 23:11 UTC
The need for some kind of relationship between changing biofuel demand and the agriculture sector (similar to what we have for the mining and ngps industries) has come up in discussions for both Brazil and Minnesota. This would require a land use linkage as well, if biofuel demand went up and land area was converted to agriculture.

**Comment by jrissman** [comment] 2020-12-04 23:17
Closing as duplicate of issue #14

**Closed by jrissman** 2020-12-04 23:17 UTC
Labels: medium priority
